//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARCHIVE_MOVE_HEAD
    {
        public decimal SRNO { get; set; }
        public string DOCNO { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<System.DateTime> TRANSDATE { get; set; }
        public string WAREHOUSENO { get; set; }
        public Nullable<int> DOCSTATUS { get; set; }
    }
}
