//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERRORMGMT_API
    {
        public int LOG_NO { get; set; }
        public string APPLICATION { get; set; }
        public string API { get; set; }
        public string APITYPE { get; set; }
        public string CONTROLLER { get; set; }
        public string ERROR_TYPE { get; set; }
        public string ERROR_MESSAGE { get; set; }
        public string ERROR_DETAILS { get; set; }
        public string ERROR_LINE { get; set; }
        public Nullable<System.DateTime> ERROR_TIME { get; set; }
        public string REMARKS { get; set; }
    }
}
