//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CC1_TEMP
    {
        public decimal SRNO { get; set; }
        public string DOCNO { get; set; }
        public string CCNO { get; set; }
        public string ZONEID { get; set; }
        public string BINNO { get; set; }
        public string BARCODE { get; set; }
        public string ITEMNO { get; set; }
        public string SERIALNO { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> USERID { get; set; }
        public string F_BINNO { get; set; }
        public string F_ZONEID { get; set; }
        public string T_BINNO { get; set; }
        public string T_ZONEID { get; set; }
        public Nullable<int> SEDSTATUS { get; set; }
        public Nullable<int> CCSTATUS { get; set; }
    }
}
