//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CLASS_SUBCLASS
    {
        public int CLASSID { get; set; }
        public string CLSNAME { get; set; }
        public int SUBCLASSID { get; set; }
        public string SUBCLSNAME { get; set; }
    }
}
