//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_USER
    {
        public int USERID { get; set; }
        public string USERNAME { get; set; }
        public string USERPASSWORD { get; set; }
        public string CLSNAME { get; set; }
        public string SUBCLSNAME { get; set; }
        public string ROLLDESC { get; set; }
        public Nullable<int> ROLLID { get; set; }
        public Nullable<int> CLSID { get; set; }
        public Nullable<int> SUBCLSSTATUS { get; set; }
        public Nullable<int> ROLLSTATUS { get; set; }
        public Nullable<int> USERSTATUS { get; set; }
        public Nullable<int> SUBCLASSID { get; set; }
    }
}
