//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAVWMSDESK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_PUTAWAY
    {
        public decimal SRNO { get; set; }
        public string DOCNO { get; set; }
        public string PUTNO { get; set; }
        public string WAREHOUSENO { get; set; }
        public string ZONEID { get; set; }
        public string BINNO { get; set; }
        public string BARCODE { get; set; }
        public string ITEMNO { get; set; }
        public string SERIALNO { get; set; }
        public string DESCRIPTION { get; set; }
        public string UOM { get; set; }
        public string QTY { get; set; }
        public Nullable<System.DateTime> RECINSERTED { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<System.DateTime> USERASSIGNDATE { get; set; }
        public Nullable<System.DateTime> TRANSDATE { get; set; }
        public Nullable<int> ARCHIVE { get; set; }
        public Nullable<int> PUTSTATUS { get; set; }
        public Nullable<bool> ASSIGNSTATUS { get; set; }
    }
}
