//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_CC_SCAN
    {
        public decimal SRNO { get; set; }
        public Nullable<System.DateTime> TRANSDATE { get; set; }
        public string WAREHOUSENO { get; set; }
        public string DOCNO { get; set; }
        public string CCNO { get; set; }
        public string BARCODE { get; set; }
        public string F_ZONEID { get; set; }
        public string F_BINNO { get; set; }
        public string T_ZONEID { get; set; }
        public string T_BINNO { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<int> PNA { get; set; }
    }
}
