//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAVWMSDESK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_SUBROLL_EDITOR
    {
        public int SUBROLLID { get; set; }
        public int ROLLID { get; set; }
        public Nullable<int> CLSID { get; set; }
        public Nullable<int> SUBCLASSID { get; set; }
        public Nullable<int> SUBCLSSTATUS { get; set; }
        public Nullable<int> ROLLSTATUS { get; set; }
    }
}
