//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAVWMSDESK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_ZONE_EDITOR
    {
        public string ZONEID { get; set; }
        public string ZONEDESC { get; set; }
        public Nullable<int> ZONESTATUS { get; set; }
    }
}
