//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAVWMSDESK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_USER_EDITOR
    {
        public int USERID { get; set; }
        public string USERNAME { get; set; }
        public string USERPASSWORD { get; set; }
        public Nullable<int> ROLLID { get; set; }
        public string STOREID { get; set; }
        public string APIURL { get; set; }
        public Nullable<int> USERSTATUS { get; set; }
    }
}
