//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAVWMSDESK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_SUBCLASS_EDITOR
    {
        public int SUBCLASSID { get; set; }
        public string SUBCLSNAME { get; set; }
        public string SUBFLAG { get; set; }
        public Nullable<int> CLASSID { get; set; }
        public Nullable<int> SUBCLSSTATUS { get; set; }
    }
}
