//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_CC_REQUEST
    {
        public decimal SRNO { get; set; }
        public string DOCNO { get; set; }
        public Nullable<System.DateTime> DOCDATE { get; set; }
        public string WAREHOUSENO { get; set; }
        public string ZONEID { get; set; }
        public string BINNO { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<System.DateTime> FDATE { get; set; }
        public Nullable<System.DateTime> TDATE { get; set; }
        public string REMARKS { get; set; }
        public Nullable<int> CLOSEDBY { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> ACHIVE { get; set; }
    }
}
