//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_CLASS_EDITOR
    {
        public int CLASSID { get; set; }
        public string CLSNAME { get; set; }
        public string CLSFLAG { get; set; }
        public Nullable<int> CLSSTATUS { get; set; }
    }
}
