//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_STOCKMOVEMENT
    {
        public decimal SRNO { get; set; }
        public string FROMBIN { get; set; }
        public string TOBIN { get; set; }
        public string TROLLEYNO { get; set; }
        public Nullable<int> WAREHOUSENO { get; set; }
        public Nullable<int> ZONEID { get; set; }
        public string BARCODE { get; set; }
        public string SKUNO { get; set; }
        public string SERIALNO { get; set; }
        public string DESCRIPTION { get; set; }
        public string UOM { get; set; }
        public Nullable<int> QTY { get; set; }
        public Nullable<int> FROMUSERID { get; set; }
        public Nullable<System.DateTime> DATE_1 { get; set; }
        public Nullable<int> TOUSERID { get; set; }
        public Nullable<System.DateTime> DATE_2 { get; set; }
        public Nullable<int> ARCHIVE { get; set; }
        public Nullable<int> STATUS { get; set; }
    }
}
