//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAVWMSDESK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_USER_TOKEN
    {
        public decimal SRNO { get; set; }
        public string TOKENID { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<System.DateTime> FDATE { get; set; }
        public Nullable<System.DateTime> TDATE { get; set; }
        public Nullable<int> INTERVAL { get; set; }
        public Nullable<int> STATUS { get; set; }
    }
}
