//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAVWMSDESK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_USER_TASKS
    {
        public decimal SRNO { get; set; }
        public string DOCNO { get; set; }
        public string SUBDOCNO { get; set; }
        public string DOCTYPE { get; set; }
        public Nullable<int> USERID { get; set; }
        public string USERNAME { get; set; }
        public Nullable<System.DateTime> ASSIGNDATE { get; set; }
    }
}
