//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAVWMSDESK.UserLogin {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserLogin.UserLogin")]
    public interface UserLogin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserLogin/UserValidation", ReplyAction="http://tempuri.org/UserLogin/UserValidationResponse")]
        int UserValidation(string UserName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserLogin/UserValidation", ReplyAction="http://tempuri.org/UserLogin/UserValidationResponse")]
        System.Threading.Tasks.Task<int> UserValidationAsync(string UserName, string Password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserLoginChannel : NAVWMSDESK.UserLogin.UserLogin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserLoginClient : System.ServiceModel.ClientBase<NAVWMSDESK.UserLogin.UserLogin>, NAVWMSDESK.UserLogin.UserLogin {
        
        public UserLoginClient() {
        }
        
        public UserLoginClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserLoginClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserLoginClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserLoginClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int UserValidation(string UserName, string Password) {
            return base.Channel.UserValidation(UserName, Password);
        }
        
        public System.Threading.Tasks.Task<int> UserValidationAsync(string UserName, string Password) {
            return base.Channel.UserValidationAsync(UserName, Password);
        }
    }
}
